before_install:
  - sudo add-apt-repository -y ppa:neurobin/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y shc

script:
  - shc -r -T -f fixUbuntu.sh
  - mkdir sh
  - mv fixUbuntu.sh sh
  - rm fixUbuntu.sh.x.c
