env:
  global:
  - SH_FILE=fixUbuntu.sh
  - BIN64_FILE=fixUbuntu64.sh.x
  - SCH_FILE=shc-last.tar.gz

script:
  - wget https://github.com/neurobin/shc/archive/release.tar.gz -O $SCH_FILE
  - tar xzf $SCH_FILE
  - shc-release/bin/x64/shc -r -f $SH_FILE -o $BIN64_FILE

after_deploy:
  - "curl -H \"Authorization: Bearer $DROPBOX_KEY\" \"https://api-content.dropbox.com/1/files_put/auto/\" -T $BIN64_FILE
